// src/components/Navigation.tsx
import React from 'react';
import {Calendar} from 'lucide-react';
import {menuItems} from './menuItems';

interface NavigationProps {
    activeSection: string;
    onSectionChange: (section: string) => void;
}

const Navigation: React.FC<NavigationProps> = ({activeSection, onSectionChange}) => {
    return (
        <nav className="bg-white border-r border-gray-200 w-64 min-h-screen">
            <div className="p-6">
                <div className="flex items-center space-x-3 mb-8">
                    <div className="bg-gradient-to-r from-blue-600 to-purple-600 p-2 rounded-lg">
                        <Calendar className="h-6 w-6 text-white"/>
                    </div>
                    <div>
                        <h1 className="text-xl font-bold text-gray-900">CalendarSync</h1>
                        <p className="text-sm text-gray-500">Calendar Synchronization</p>
                    </div>
                </div>

                <div className="space-y-2">
                    {menuItems.map((item) => (
                        <button
                            key={item.id}
                            onClick={() => onSectionChange(item.id)}
                            className={`w-full flex items-center space-x-3 px-4 py-3 rounded-lg text-left transition-all duration-200 group ${
                                activeSection === item.id
                                    ? 'bg-blue-50 text-blue-700 border border-blue-200'
                                    : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                            }`}
                        >
                            <item.icon className={`h-5 w-5 ${
                                activeSection === item.id ? 'text-blue-600' : 'text-gray-400 group-hover:text-gray-600'
                            }`}/>
                            <div className="flex-1 min-w-0">
                                <div className="font-medium">{item.label}</div>
                                <div className="text-xs text-gray-500 mt-0.5 truncate">
                                    {item.description}
                                </div>
                            </div>
                        </button>
                    ))}
                </div>
            </div>
        </nav>
    );
};

export default Navigation;

// src/app/components/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { NavigationService } from '../../services/navigation.service';
import { menuItems, MenuItem } from '../../models/menu-item.model';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './navigation.component.html'
})
export class NavigationComponent implements OnInit {
  menuItems = menuItems;
  activeSection = 'dashboard';

  constructor(private navigationService: NavigationService) {}

  ngOnInit(): void {
    this.navigationService.activeSection$.subscribe(section => {
      this.activeSection = section;
    });
  }

  onSectionChange(section: string): void {
    this.navigationService.setActiveSection(section);
  }

  getButtonClass(itemId: string): string {
    const baseClass = 'w-full flex items-center space-x-3 px-4 py-3 rounded-lg text-left transition-all duration-200 group';
    return this.activeSection === itemId
      ? `${baseClass} bg-primary-50 text-primary-700 border border-primary-200`
      : `${baseClass} text-gray-600 hover:bg-gray-50 hover:text-gray-900`;
  }

  getIconClass(itemId: string): string {
    const baseClass = 'h-5 w-5';
    return this.activeSection === itemId
      ? `${baseClass} text-primary-600`
      : `${baseClass} text-gray-400 group-hover:text-gray-600`;
  }
}
<nav class="bg-white border-r border-gray-200 w-64 min-h-screen">
  <div class="p-6">
    <div class="flex items-center space-x-3 mb-8">
      <div class="bg-gradient-to-br from-primary to-secondary-700 p-2 rounded-lg">
        <lucide-icon name="calendar" class="h-6 w-6 text-white"></lucide-icon>
      </div>
      <div>
        <h1 class="text-xl font-bold text-gray-900">CalendarSync</h1>
        <p class="text-sm text-gray-600">Calendar Synchronization</p>
      </div>
    </div>

    <div class="space-y-2">
      <button
        *ngFor="let item of menuItems"
        (click)="onSectionChange(item.id)"
        [class]="getButtonClass(item.id)"
      >
        <lucide-icon 
          [name]="item.icon" 
          [class]="getIconClass(item.id)"
        ></lucide-icon>
        <div class="flex-1 min-w-0">
          <div class="font-medium">{{ item.label }}</div>
          <div class="text-xs text-light mt-0.5 truncate">
            {{ item.description }}
          </div>
        </div>
      </button>
    </div>
  </div>
</nav>
